import type { Metadata } from 'next'
import './globals.css'
import SideNav from './dashboard/page'
import { inter } from './font'


export const metadata: Metadata = {
  title: 'social media app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={`  h-[100vh] flex gap-2 ${inter.className} `}>
      <SideNav />
        {children}
      </body>
    </html>
  )
}
